// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQDth2t8LUi3VfZ6tjFo8of8VRb7DX-E',
    appId: '1:1035535362739:web:19d9f84ba17735c9311ec6',
    messagingSenderId: '1035535362739',
    projectId: 'ucsapp-2e572',
    authDomain: 'ucsapp-2e572.firebaseapp.com',
    storageBucket: 'ucsapp-2e572.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4i11I__LzCs0mmNos3DcUiJrEHdqfSoc',
    appId: '1:1035535362739:android:632382dd53d8903d311ec6',
    messagingSenderId: '1035535362739',
    projectId: 'ucsapp-2e572',
    storageBucket: 'ucsapp-2e572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClH_6Q1cj1WdfG95TSI_8_xdaqP7iJpq8',
    appId: '1:1035535362739:ios:f31bc27243488554311ec6',
    messagingSenderId: '1035535362739',
    projectId: 'ucsapp-2e572',
    storageBucket: 'ucsapp-2e572.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClH_6Q1cj1WdfG95TSI_8_xdaqP7iJpq8',
    appId: '1:1035535362739:ios:f31bc27243488554311ec6',
    messagingSenderId: '1035535362739',
    projectId: 'ucsapp-2e572',
    storageBucket: 'ucsapp-2e572.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPQDth2t8LUi3VfZ6tjFo8of8VRb7DX-E',
    appId: '1:1035535362739:web:751b7664921b179d311ec6',
    messagingSenderId: '1035535362739',
    projectId: 'ucsapp-2e572',
    authDomain: 'ucsapp-2e572.firebaseapp.com',
    storageBucket: 'ucsapp-2e572.firebasestorage.app',
  );
}
